### ISSUE TITLE
Only first line is returned

### ISSUE THREAD

**Issue by adminterra** [karelnagel/gpt-3#1]
The following prompt:
```
python function that takes an argument file and returns out the first 10 words
```
returned the following code:
```
def first_ten_words
```

This seems to be a part of a correct response, bit I only got a single line.

**Comment by karelnagel** [comment]
Try changing gpt3.maxTokens in settings.json or Max Tokens in extension settings to a bigger value, like maybe 100. 6 is currently the default value but should be updated to a bigger value, let me know if it solves your issue and I will also change the default 🙂
