### ISSUE TITLE
Generated code contains html encoded characters

### ISSUE THREAD

**Issue by WesselKroos** [karelnagel/gpt-3#2]
Using Gpt3 model text-davinci-003
![image](https://user-images.githubusercontent.com/31220528/205964556-68d4b281-e07b-4fbe-b998-55e674ff8b55.png)

Html encoded characters are generated instead of the decoded characters:
![image](https://user-images.githubusercontent.com/31220528/205964346-37471361-5e25-4113-9eaf-231d2e0e93be.png)

~~And the end of the generated code contains a `</code>` text:
![image](https://user-images.githubusercontent.com/31220528/205964832-c3cd1cb6-a099-4df5-bdc4-841dffe81a9b.png)~~
- The `</code>` text was generated by a html extension that automatically generates closing tags.

**Comment by karelnagel** [comment]
Okay will fix that

**Comment by karelnagel** [comment]
Just tried it and for my prompts it worked fine 
![image](https://user-images.githubusercontent.com/65607486/206467370-963d4225-6b7f-420b-92c4-0df3e6ea8fdf.png)
So maybe GPT was giving this output on purpose, but also pushed an update that will replace all gt and lt tags.
